# Generated by Django 5.0.6 on 2025-11-12 06:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_sku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('campaign_type', models.CharField(choices=[('product_promotion', 'Product Promotion'), ('brand_awareness', 'Brand Awareness'), ('seasonal_sale', 'Seasonal Sale'), ('new_product', 'New Product Launch'), ('event', 'Event Promotion'), ('custom', 'Custom Campaign')], default='product_promotion', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('target_audience', models.TextField(blank=True, help_text='AI-generated or manual target audience description')),
                ('target_age_min', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(100)])),
                ('target_age_max', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(100)])),
                ('target_gender', models.CharField(blank=True, choices=[('all', 'All'), ('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('target_locations', models.TextField(blank=True, help_text='Comma-separated locations')),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('use_ai_content', models.BooleanField(default=True, help_text='Use AI to generate content')),
                ('ai_style', models.CharField(blank=True, help_text='AI style preference (e.g., professional, casual, creative)', max_length=100)),
                ('ai_tone', models.CharField(blank=True, help_text='AI tone preference (e.g., friendly, formal, humorous)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ad_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('poster', 'Poster/Image'), ('video', 'Video'), ('text', 'Text Post'), ('carousel', 'Carousel'), ('story', 'Story')], default='poster', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('call_to_action', models.CharField(blank=True, max_length=100)),
                ('hashtags', models.TextField(blank=True, help_text='AI-generated hashtags')),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisements/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='advertisements/videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='advertisements/thumbnails/')),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_prompt', models.TextField(blank=True, help_text='Prompt used for AI generation')),
                ('ai_model', models.CharField(blank=True, help_text='AI model used', max_length=100)),
                ('generation_time', models.DateTimeField(blank=True, null=True)),
                ('custom_text', models.TextField(blank=True, help_text='Custom text overlay')),
                ('text_color', models.CharField(default='#000000', help_text='Hex color code', max_length=7)),
                ('background_color', models.CharField(default='#FFFFFF', help_text='Hex color code', max_length=7)),
                ('font_style', models.CharField(blank=True, default='Arial', max_length=50)),
                ('font_size', models.IntegerField(default=24, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(200)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='marketing.adcampaign')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_contents', to='products.product')),
            ],
            options={
                'db_table': 'ad_contents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_type', models.CharField(choices=[('text', 'Text Generation'), ('image', 'Image Generation'), ('video', 'Video Generation'), ('hashtags', 'Hashtag Generation'), ('cta', 'CTA Generation')], max_length=50)),
                ('prompt', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('ai_model', models.CharField(max_length=100)),
                ('tokens_used', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='marketing.adcampaign')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='marketing.adcontent')),
            ],
            options={
                'db_table': 'ai_generation_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('tiktok', 'TikTok')], max_length=20)),
                ('account_name', models.CharField(max_length=200)),
                ('account_id', models.CharField(blank=True, help_text='Platform account ID', max_length=200)),
                ('page_id', models.CharField(blank=True, help_text='Page/Profile ID', max_length=200)),
                ('access_token', models.TextField(blank=True, help_text='OAuth access token')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('profile_picture', models.URLField(blank=True)),
                ('follower_count', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_media_accounts',
                'ordering': ['platform', 'account_name'],
                'unique_together': {('platform', 'account_id', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_post_id', models.CharField(blank=True, help_text='Post ID from platform', max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('published_time', models.DateTimeField(blank=True, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error if post failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='marketing.adcampaign')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='marketing.adcontent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='marketing.socialmediaaccount')),
            ],
            options={
                'db_table': 'social_media_posts',
                'ordering': ['-scheduled_time', '-created_at'],
            },
        ),
    ]

