# Generated by Django 5.0.6 on 2025-11-11 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnitem',
            name='po_item',
            field=models.ForeignKey(blank=True, help_text='Related PO item (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_items', to='purchases.purchaseorderitem'),
        ),
    ]
