# Generated by Django 5.0.6 on 2025-11-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='return_number',
            field=models.CharField(blank=True, help_text='Auto-generated if not provided', max_length=50, unique=True),
        ),
    ]
