# Generated by Django 5.0.6 on 2025-11-09 09:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total credit given', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outstanding balance', max_digits=10)),
                ('last_transaction_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to='billing.customer')),
            ],
            options={
                'db_table': 'customer_credits',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit Given'), ('payment', 'Payment Received'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='billing.invoice')),
                ('customer_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='credit_ledger.customercredit')),
            ],
            options={
                'db_table': 'credit_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_credit'], name='credit_tran_custome_4949dd_idx'), models.Index(fields=['transaction_type'], name='credit_tran_transac_0eee54_idx'), models.Index(fields=['created_at'], name='credit_tran_created_d7035f_idx')],
            },
        ),
    ]
