# Generated by Django 5.0.6 on 2025-11-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=100, unique=True)),
                ('data', models.JSONField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_cache',
                'indexes': [models.Index(fields=['cache_key'], name='analytics_c_cache_k_e23405_idx'), models.Index(fields=['expires_at'], name='analytics_c_expires_872975_idx')],
            },
        ),
    ]
