# Generated by Django 5.0.6 on 2025-11-11 17:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 4217 currency code (e.g., USD, INR, EUR)', max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(help_text='Currency symbol (e.g., $, ₹, €)', max_length=10)),
                ('is_base_currency', models.BooleanField(default=False, help_text='Base currency for the system')),
                ('is_active', models.BooleanField(default=True)),
                ('decimal_places', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)])),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Exchange rate relative to base currency', max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'db_table': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('date', models.DateField()),
                ('source', models.CharField(blank=True, help_text='Source of exchange rate (e.g., API, Manual)', max_length=100)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='currencies.currency')),
            ],
            options={
                'db_table': 'exchange_rate_history',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['currency', 'date'], name='exchange_ra_currenc_7b11fd_idx')],
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
