# Generated by Django 5.0.6 on 2025-11-11 17:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0003_customercommunication_customerpurchasehistory_and_more'),  # Changed to depend on 0003
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('alternate_phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('gstin', models.CharField(blank=True, help_text='GST Identification Number', max_length=15)),
                ('pan', models.CharField(blank=True, help_text='PAN Number', max_length=10)),
                ('customer_type', models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('wholesale', 'Wholesale'), ('retail', 'Retail')], default='regular', max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum credit amount allowed', max_digits=10)),
                ('loyalty_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_purchases', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_orders', models.IntegerField(default=0)),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('anniversary_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about customer')),
                ('is_active', models.BooleanField(default=True)),
                ('is_blacklisted', models.BooleanField(default=False, help_text='Blacklist customer if needed')),
                ('blacklist_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers_enhanced',
                'ordering': ['-created_at'],
            },
        ),
        # CustomerCommunication and CustomerPurchaseHistory already exist from billing.0003
        # Use SeparateDatabaseAndState to register them in Django state without creating tables
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Tables already exist, so no database operations needed
            ],
            state_operations=[
                migrations.CreateModel(
                    name='CustomerCommunication',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('communication_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('call', 'Phone Call'), ('visit', 'In-Store Visit')], max_length=20)),
                        ('subject', models.CharField(blank=True, max_length=200)),
                        ('message', models.TextField()),
                        ('sent_at', models.DateTimeField(auto_now_add=True)),
                        ('is_read', models.BooleanField(default=False)),
                        ('read_at', models.DateTimeField(blank=True, null=True)),
                        ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='customers.customer')),
                        ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'customer_communications',
                        'ordering': ['-sent_at'],
                    },
                ),
                migrations.CreateModel(
                    name='CustomerPurchaseHistory',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('items_count', models.IntegerField(default=0)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='customers.customer')),
                        ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_history', to='billing.invoice')),
                    ],
                    options={
                        'db_table': 'customer_purchase_history',
                        'ordering': ['-created_at'],
                    },
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='customers_e_phone_4144ee_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='customers_e_email_a68448_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type'], name='customers_e_custome_4ae915_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active'], name='customers_e_is_acti_8195ee_idx'),
        ),
        migrations.AddIndex(
            model_name='customercommunication',
            index=models.Index(fields=['customer', 'sent_at'], name='customer_co_custome_85d74a_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpurchasehistory',
            index=models.Index(fields=['customer', 'created_at'], name='customer_pu_custome_0c162a_idx'),
        ),
    ]
