# Generated by Django 5.0.6 on 2025-11-11 17:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0003_customercommunication_customerpurchasehistory_and_more'),  # Changed to depend on 0003
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('alternate_phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('gstin', models.CharField(blank=True, help_text='GST Identification Number', max_length=15)),
                ('pan', models.CharField(blank=True, help_text='PAN Number', max_length=10)),
                ('customer_type', models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('wholesale', 'Wholesale'), ('retail', 'Retail')], default='regular', max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum credit amount allowed', max_digits=10)),
                ('loyalty_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_purchases', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_orders', models.IntegerField(default=0)),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('anniversary_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about customer')),
                ('is_active', models.BooleanField(default=True)),
                ('is_blacklisted', models.BooleanField(default=False, help_text='Blacklist customer if needed')),
                ('blacklist_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers_enhanced',
                'ordering': ['-created_at'],
            },
        ),
        # CustomerCommunication and CustomerPurchaseHistory are defined in billing app
        # They are already created by billing.0003 migration, so we don't create them here
        # The customers app just re-exports them from billing.models
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='customers_e_phone_4144ee_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='customers_e_email_a68448_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type'], name='customers_e_custome_4ae915_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active'], name='customers_e_is_acti_8195ee_idx'),
        ),
    ]
