# Generated by Django 5.0.6 on 2025-11-11 17:03
# Modified: This migration is empty because the Customer model is managed by the billing app.
# The customers app only re-exports models from billing.models for backward compatibility.

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0003_customercommunication_customerpurchasehistory_and_more'),
    ]

    operations = [
        # No operations needed - Customer, CustomerCommunication, and CustomerPurchaseHistory
        # are all managed by the billing app. The customers app just re-exports them.
    ]
