# Generated by Django 5.0.6 on 2025-11-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpurchasehistory',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customercommunication',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customercommunication',
            name='sent_by',
        ),
        migrations.RemoveField(
            model_name='customerpurchasehistory',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='CustomerCommunication',
        ),
        migrations.DeleteModel(
            name='CustomerPurchaseHistory',
        ),
    ]
