# Generated by Django 5.0.6 on 2025-11-09 09:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'warehouses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('reserved_quantity', models.IntegerField(default=0, help_text='Quantity reserved for pending orders', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.product')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_updates', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'stocks',
                'indexes': [models.Index(fields=['product', 'warehouse'], name='stocks_product_77ef58_idx'), models.Index(fields=['quantity'], name='stocks_quantit_bee17c_idx')],
                'unique_together': {('product', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer'), ('damage', 'Damage'), ('expired', 'Expired')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for addition, negative for deduction')),
                ('reference_number', models.CharField(blank=True, help_text='Invoice ID, Purchase Order, etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'warehouse'], name='inventory_t_product_5f2b4b_idx'), models.Index(fields=['transaction_type'], name='inventory_t_transac_a372b6_idx'), models.Index(fields=['created_at'], name='inventory_t_created_f087fb_idx')],
            },
        ),
    ]
