# Generated by Django 5.0.6 on 2025-11-11 17:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='expenses.expensecategory')),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
                'db_table': 'expense_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('upi', 'UPI'), ('credit_card', 'Credit Card')], default='cash', max_length=20)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_tax_deductible', models.BooleanField(default=True, help_text='Can this expense be deducted from tax?')),
                ('expense_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('vendor_gstin', models.CharField(blank=True, max_length=15)),
                ('bill_number', models.CharField(blank=True, max_length=100)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='expenses/receipts/')),
                ('bill_document', models.FileField(blank=True, null=True, upload_to='expenses/bills/')),
                ('notes', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory')),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-expense_date'],
                'indexes': [models.Index(fields=['expense_number'], name='expenses_expense_003f04_idx'), models.Index(fields=['category'], name='expenses_categor_80dcb8_idx'), models.Index(fields=['expense_date'], name='expenses_expense_43600a_idx'), models.Index(fields=['is_recurring'], name='expenses_is_recu_7c3a89_idx')],
            },
        ),
    ]
