# Generated by Django 5.0.6 on 2025-11-11 17:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend', models.CharField(blank=True, choices=[('increasing', 'Increasing'), ('decreasing', 'Decreasing'), ('stable', 'Stable'), ('seasonal', 'Seasonal')], max_length=20)),
                ('seasonality_factor', models.DecimalField(blank=True, decimal_places=2, help_text='Seasonality multiplier', max_digits=5, null=True)),
                ('average_daily_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('average_weekly_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('average_monthly_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('average_lead_time', models.IntegerField(default=0, help_text='Average lead time in days')),
                ('recommended_safety_stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('recommended_reorder_point', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('recommended_order_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_analyzed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_patterns', to='products.product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demand_patterns', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'demand_patterns',
                'indexes': [models.Index(fields=['product'], name='demand_patt_product_d699f6_idx'), models.Index(fields=['trend'], name='demand_patt_trend_c69ce8_idx')],
                'unique_together': {('product', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='OptimalStockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimal_min_stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('optimal_max_stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('optimal_reorder_point', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('optimal_reorder_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('current_stock', models.IntegerField(default=0)),
                ('stock_status', models.CharField(choices=[('optimal', 'Optimal'), ('low', 'Low'), ('high', 'High'), ('critical', 'Critical')], default='optimal', max_length=20)),
                ('calculation_method', models.CharField(blank=True, max_length=50)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimal_stock_levels', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimal_stock_levels', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'optimal_stock_levels',
                'indexes': [models.Index(fields=['product', 'warehouse'], name='optimal_sto_product_4ae484_idx'), models.Index(fields=['stock_status'], name='optimal_sto_stock_s_06c336_idx')],
                'unique_together': {('product', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='SalesForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20)),
                ('predicted_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('predicted_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('confidence_level', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Confidence level (0-100)', max_digits=5)),
                ('actual_quantity', models.IntegerField(blank=True, null=True)),
                ('actual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('forecast_method', models.CharField(blank=True, help_text="Method used for forecasting (e.g., 'moving_average', 'exponential_smoothing')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='products.product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'sales_forecasts',
                'ordering': ['-forecast_date'],
                'indexes': [models.Index(fields=['product', 'forecast_date'], name='sales_forec_product_90681d_idx'), models.Index(fields=['warehouse', 'forecast_date'], name='sales_forec_warehou_c52f07_idx')],
                'unique_together': {('product', 'warehouse', 'forecast_date', 'period_type')},
            },
        ),
    ]
