# Generated by Django 5.0.6 on 2025-11-09 09:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayBookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry_type', models.CharField(choices=[('sale', 'Sale'), ('return', 'Return'), ('payment', 'Payment'), ('credit', 'Credit'), ('expense', 'Expense')], max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daybook_entries', to='billing.invoice')),
            ],
            options={
                'db_table': 'daybook_entries',
                'ordering': ['date', 'created_at'],
                'indexes': [models.Index(fields=['date'], name='daybook_ent_date_452002_idx'), models.Index(fields=['entry_type'], name='daybook_ent_entry_t_265990_idx')],
            },
        ),
    ]
